In [7]:
from IPython.display import clear_output
from matplotlib import pyplot as plt
import numpy as np
%matplotlib inline
np.seterr(divide='ignore')

def live_plot(data_dict, figsize=(7,5), title=''):
    clear_output(wait=True)
    plt.figure(figsize=figsize)
    for label,data in data_dict.items():
        plt.plot(data, label=label)
    plt.title(title)
    plt.grid(True)
    plt.xlabel('epoch')
    plt.legend(loc='center left') # the plot evolves to the right
    plt.show();

error = {   
        'TE01':'Type Error: Requires format = iterble of size 2',
        'TE02':'Type Error: Requires format = float',
        'VE01':'Value Error: Distance has a value of 0'
        }


class ball():
    def __init__(self, position = tuple, velocity = tuple, mass = float) -> None:
        if len(position) != 2:
            raise TypeError(error['TE01'])
        else:
            self._position = np.array(position)
        if len(position) != 2:
            raise TypeError(error['TE01'])
        else:
            self._velocity = np.array(velocity)
        if type(mass) == float or type(mass) == int:
            self._mass = float(mass)
        else:
            raise TypeError(error['TE02'])

    @property
    def position(self):
        return self._position
    
    @position.setter
    def position(self, position = tuple):
        if len(position) != 2:
            raise TypeError(error['TE01'])
        else:
            self._position = np.array(position)

    @property
    def velocity(self):
        return self._velocity

    @velocity.setter
    def velocity(self, velocity = tuple):
        if len(velocity) != 2:
            raise TypeError(error['TE01'])
        else:
            self._velocity = np.array(velocity)               
    
    @property
    def mass(self):
        return self._mass

    @mass.setter
    def mass(self, mass):
        if type(mass) != float:
            raise TypeError(error['TE02'])
        else:
            self._mass = float(mass)       

    def force_between(self, ball, scale = 6.6743 * 10**-11):
        dist = np.linalg.norm(self._position-ball.position)
        vector = ball.position - self._position
        force = scale*self._mass*ball.mass/np.square(dist)
        if vector[1] < 0:
            try:
                alpha_prime = vector[1]/vector[0] + np.pi
            except:
                return force*np.array((0,-1)), -force*np.array((0,-1))
        else:
            try:
                alpha_prime = vector[1]/vector[0]
            except:
                return force*np.array((0,1)), -force*np.array((0,1))
        force_vector = force*np.array((np.cos(np.arctan(alpha_prime)),np.sin(np.arctan(alpha_prime))))
        return force_vector, -force_vector
    
def update(balls):
    while True:
        pass

In [8]:
ball1 = ball((0,0),(0,0),1)
ball2 = ball((10,10),(0,0),1)
ball3 = ball((10,0),(0,0),1)
ball4 = ball((0,10),(0,0),1)

balls = [ball1, ball2, ball3, ball4]

scale = 1
time_step = 0.1

In [10]:
forces = [[] for _ in range(len(balls))]

for ball in range(len(balls)):
    for other_ball in range(ball+1,len(balls)):
        force_ball, force_other_ball = balls[ball].force_between(balls[other_ball], scale)
        forces[ball].append(force_ball)
        forces[other_ball].append(force_other_ball)

In [12]:
forces =[sum(force) for force in forces]

In [13]:
forces

[array([0.01353553, 0.01353553]),
 array([ 0.00646447, -0.01353553]),
 array([-0.00646447,  0.00646447]),
 array([-0.01353553, -0.00646447])]